### ISSUE TITLE
Android version not compiling

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#33]
The Android version is not compiling as follows:

Server exception
Project "look-out-for-me.tmp.proj" (default targets): android Build Tooling revision 2015.09.30.2r Warning: Error during processing of action! Attempting to revert... Warning: Failed to install 'cordova-plugin-android-support-v4':Error: Uh oh! "/tmp/builds/NfduTAA794UERhJLdY/app/libs/android-support-v4.jar" already exists! at Object.module.exports.common.copyNewFile (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/platforms/common.js:67:19) at Object.module.exports.source-file.install (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/platforms/android.js:78:20) at installWrapper (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/platforms/platforms.js:77:32) at Object.ActionStack.process (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/util/action-stack.js:68:25) at handleInstall (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:580:20) at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:367:28 at _fulfilled (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:749:13) at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:509:49 Warning: Failed to install 'de.appplant.cordova.plugin.local-notification':Error: Uh oh! "/tmp/builds/NfduTAA794UERhJLdY/app/libs/android-support-v4.jar" already exists! at Object.module.exports.common.copyNewFile (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/platforms/common.js:67:19) at Object.module.exports.source-file.install (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/platforms/android.js:78:20) at installWrapper (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/platforms/platforms.js:77:32) at Object.ActionStack.process (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/util/action-stack.js:68:25) at handleInstall (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:580:20) at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:367:28 at _fulfilled (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:749:13) at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:509:49 Warning: Uh oh! "/tmp/builds/NfduTAA794UERhJLdY/app/libs/android-support-v4.jar" already exists! Warning: /home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:189 Warning: throw Error("exit code: " + code); ^ Warning: Error: exit code: 1 at Error (<anonymous>) at ChildProcess.<anonymous> (/home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:189:14) at ChildProcess.emit (events.js:98:17) at Process.ChildProcess._handle.onexit (child_process.js:810:12) Error: Build failed during execution Error: 'Build failed with error code 8' Done building project "look-out-for-me.tmp.proj" -- FAILED.

**Comment by slightlydiff** [comment]
Two issues found:

1 Android-support-v4.jar is included in three places; Push Notification, Local Notification and the AppFeedback causing the compiler to complain.  Therefore the Push Notification and Local Notification plugins have been removed from the market place, downloaded, manually adapted as follows and manually re-imported.  Manual updates will not need to be applied as new versions are released.
Push Notification plugin
```
From:
<source-file src="src/android/com/plugin/android-support-v4.jar" target-dir="libs/"/>
To:
<!--<source-file src="src/android/com/plugin/android-support-v4.jar" target-dir="libs/"/>-->
```
Local Notifications plugin
```
From:
<dependency id="cordova-plugin-android-support-v4" />
To:
<!--<dependency id="cordova-plugin-android-support-v4" />-->
```

2 Having both normal Android Splash screens and 9Patch Splash Screens in the same properties page although allowed in AppBuilder is not supported and causes the compiler to fail.  Therefore 9Patch Splash Screens have been removed from this project
